Feature/49 implement new imap group of commands
G1ANT-Robot/G1ANT.Addon.Net pull request #7
Opened 2019-08-22 14:25 UTC by przegwar

2019-08-22 14:30 UTC, danieladamkaiser commented on G1ANT.Addon.Net/Commands/ImapCloseCommand.cs
> +﻿
empty line

2019-08-22 14:30 UTC, danieladamkaiser commented on G1ANT.Addon.Net/Commands/ImapCloseCommand.cs
> +
emptier lien

2019-08-22 14:30 UTC, danieladamkaiser commented on G1ANT.Addon.Net/Commands/ImapCloseCommand.cs
> +
bro wtf
empty line
plis fix

2019-08-22 14:30 UTC, danieladamkaiser commented on G1ANT.Addon.Net/Commands/ImapCloseCommand.cs
> +
and more wtf

2019-08-22 14:58 UTC, danieladamkaiser requested changes

2019-08-22 14:58 UTC, danieladamkaiser commented on G1ANT.Addon.Net/Commands/ImapCloseCommand.cs
> +using G1ANT.Language;
Move usings after license info

2019-08-22 14:58 UTC, danieladamkaiser commented on G1ANT.Addon.Net/Commands/ImapGetEmailsCommand.cs
> +    [Command(Name = "imap.getmails", Tooltip = "This command uses the IMAP protocol to check an email inbox and allows the user to analyze their messages received within a specified time span, with t
Random spelling of IMAP (upper, lower cases)- make it consistent in Tooltips

2019-08-22 14:58 UTC, danieladamkaiser commented on G1ANT.Addon.Net/Commands/ImapGetEmailsCommand.cs
> +            [Argument(Required = false, Tooltip = "Name of a list variable where the returned mail variables will be stored")]
I believe all required tags are redundant, especially when you provide command with default value of argument

2019-08-22 14:58 UTC, danieladamkaiser commented on G1ANT.Addon.Net/Commands/ImapGetEmailsCommand.cs
> +            [Argument(Required = false, Tooltip = "Mark analyzed messages as read")]
wtf are analyzed messages?

2019-08-23 10:46 UTC, lfronczyk commented on G1ANT.Addon.Net/ImapHelper.cs
>      public static class ImapHelper
Make it non-static `ImapConnectionManager` or `ImapManager`. You can make it a singleton (blah).

2019-08-23 10:47 UTC, danieladamkaiser commented on G1ANT.Addon.Net/Commands/ImapReconnectCommand.cs
> +using G1ANT.Language;
Empty lines
move usings after license info

2019-08-23 10:59 UTC, danieladamkaiser approved these changes

2019-08-23 12:10 UTC, lfronczyk commented on G1ANT.Addon.Net/ImapManager.cs
> +        private static ImapManager _instance = null;
```csharp
static ImapManager Instance { get; } = new ImapManager()
```

2019-08-23 12:12 UTC, lfronczyk approved these changes

2019-08-23 12:16 UTC, merged